<?php
// disconnect.php — undoes what connect.php did. Pure logic, JSON I/O.

declare(strict_types=1);

function parse_args(array $argv): array {
    $args = [];
    foreach (array_slice($argv, 1) as $a) {
        if (preg_match('/^--([^=]+)(?:=(.*))?$/', $a, $m)) {
            $args[$m[1]] = $m[2] ?? true;
        }
    }
    return $args;
}

function emit(array $data): void {
    echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
    exit(0);
}

$args = parse_args($argv);
$force = isset($args['force']) ? (string)$args['force'] : null; // null | 'symlink-elsewhere' | 'orphan-wrapper' | 'real-dir'

$report = [
    'status' => 'ok',
    'symlink' => ['action' => 'skipped'],
    'wrappers' => [],
    'bin_dir' => 'skipped',
    'claude_md' => ['action' => 'skipped'],
    'warnings' => [],
];

// ---------- Parse CLAUDE.md for site_path ----------

$claudePath = 'CLAUDE.md';
$claude = is_file($claudePath) ? (string)file_get_contents($claudePath) : '';
$start = '<!-- localwp-connect:start -->';
$end   = '<!-- localwp-connect:end -->';

$sitePath = null;
$siteName = null;
$si = $claude === '' ? false : strpos($claude, $start);
$ei = $claude === '' ? false : strpos($claude, $end);
$hasBlock = ($si !== false && $ei !== false && $ei > $si);

if ($hasBlock) {
    $block = substr($claude, $si, $ei - $si);
    if (preg_match('/##\s+LocalWP Site:\s*(.+)/', $block, $m)) $siteName = trim($m[1]);
    if (preg_match('/\*\*Site path:\*\*\s*`([^`]+)`/', $block, $m)) $sitePath = trim($m[1]);
}

// ---------- Symlink ----------

if ($sitePath) {
    $slug = basename((string)getcwd());
    $target = rtrim($sitePath, '/\\') . '/app/public/wp-content/plugins/' . $slug;
    $report['symlink']['target'] = $target;
    $isWin = PHP_OS_FAMILY === 'Windows';
    $pwdReal = realpath((string)getcwd()) ?: (string)getcwd();

    if (!file_exists($target) && !is_link($target)) {
        $report['symlink']['action'] = 'already_absent';
    } elseif ($isWin) {
        // On Windows, PHP's is_link() is unreliable for junctions (mklink /J) AND directory symlinks
        // (mklink /D) — both are NTFS reparse points, which PHP doesn't always recognize.
        // Use fsutil to detect + read the real target.
        $jt = win_reparse_target($target);
        if ($jt !== null) {
            $jtReal = realpath($jt) ?: $jt;
            if (win_path_eq($jtReal, $pwdReal)) {
                @rmdir($target);
                $report['symlink']['action'] = !file_exists($target) ? 'removed' : 'error_still_present';
            } elseif ($force === 'symlink-elsewhere') {
                @rmdir($target);
                $report['symlink']['action'] = 'removed_foreign';
                $report['symlink']['was_pointing_to'] = $jtReal;
            } else {
                $report['symlink']['action'] = 'blocked_symlink_elsewhere';
                $report['symlink']['was_pointing_to'] = $jtReal;
                $report['warnings'][] = "Junction/symlink at $target points to $jtReal, not this project — left in place";
            }
        } elseif (is_dir($target)) {
            $report['symlink']['action'] = 'blocked_real_directory';
            $report['warnings'][] = "Real directory at $target — left in place (not a junction or symlink)";
        } else {
            $report['symlink']['action'] = 'blocked_unexpected_file';
            $report['warnings'][] = "Unexpected file at $target — left in place";
        }
    } elseif (is_link($target)) {
        $cur = readlink($target) ?: '';
        $curReal = realpath($cur) ?: $cur;
        if ($curReal === $pwdReal) {
            @unlink($target);
            $report['symlink']['action'] = (!file_exists($target) && !is_link($target))
                ? 'removed' : 'error_still_present';
        } elseif ($force === 'symlink-elsewhere') {
            @unlink($target);
            $report['symlink']['action'] = 'removed_foreign';
            $report['symlink']['was_pointing_to'] = $curReal;
        } else {
            $report['symlink']['action'] = 'blocked_symlink_elsewhere';
            $report['symlink']['was_pointing_to'] = $curReal;
            $report['warnings'][] = "Symlink at $target points to $curReal, not this project — left in place";
        }
    } elseif (is_dir($target)) {
        $report['symlink']['action'] = 'blocked_real_directory';
        $report['warnings'][] = "Real directory at $target — left in place (not a symlink)";
    } else {
        $report['symlink']['action'] = 'blocked_unexpected_file';
        $report['warnings'][] = "Unexpected file at $target — left in place";
    }
} else {
    $report['symlink']['action'] = 'skipped_no_site_path';
    if ($hasBlock) $report['warnings'][] = "CLAUDE.md block found but site path not parseable";
}

// ---------- Wrappers ----------

$header = 'Auto-generated by localwp-connect';
foreach (['bin/wp', 'bin/wp.cmd'] as $wrapper) {
    $entry = ['path' => $wrapper];
    if (!is_file($wrapper)) {
        $entry['action'] = 'skipped_absent';
    } else {
        $head = (string)@file_get_contents($wrapper, false, null, 0, 512);
        if (str_contains($head, $header)) {
            @unlink($wrapper);
            $entry['action'] = is_file($wrapper) ? 'error_still_present' : 'removed';
        } elseif ($force === 'orphan-wrapper') {
            @unlink($wrapper);
            $entry['action'] = is_file($wrapper) ? 'error_still_present' : 'removed_forced';
        } else {
            $entry['action'] = 'orphan_kept';
            $report['warnings'][] = "$wrapper has no localwp-connect header — left in place (may be hand-written)";
        }
    }
    $report['wrappers'][] = $entry;
}

// Remove bin/ if empty
if (is_dir('bin')) {
    $entries = array_diff(scandir('bin') ?: [], ['.', '..']);
    if (!$entries) {
        @rmdir('bin');
        $report['bin_dir'] = is_dir('bin') ? 'error_still_present' : 'removed_empty';
    } else {
        $report['bin_dir'] = 'kept_not_empty';
    }
}

// ---------- CLAUDE.md block ----------

if ($claude !== '' && $hasBlock) {
    $before = rtrim(substr($claude, 0, $si), "\n");
    $after  = ltrim(substr($claude, $ei + strlen($end)), "\n");
    $new = $before === '' ? $after : ($after === '' ? $before . "\n" : $before . "\n\n" . $after);
    if (trim($new) === '') {
        @unlink($claudePath);
        $report['claude_md']['action'] = is_file($claudePath) ? 'error_still_present' : 'file_deleted_empty';
    } else {
        file_put_contents($claudePath, $new);
        $report['claude_md']['action'] = 'block_removed';
    }
} elseif ($claude === '') {
    $report['claude_md']['action'] = 'skipped_no_file';
} else {
    $report['claude_md']['action'] = 'skipped_no_markers';
}

$report['site_name'] = $siteName;
$report['site_path'] = $sitePath;

emit($report);

// ---------- Windows reparse-point helpers ----------

/**
 * If $path is an NTFS reparse point (junction or directory symlink), return its target.
 * Returns null if $path is not a reparse point (real dir, file, or missing) or we're not on Windows.
 *
 * Uses `fsutil reparsepoint query` which ships with every supported Windows version and does not
 * require elevation. Parses the "Print Name:" line.
 */
function win_reparse_target(string $path): ?string {
    if (PHP_OS_FAMILY !== 'Windows') return null;
    $out = [];
    $rc = 0;
    @exec('fsutil reparsepoint query ' . escapeshellarg($path) . ' 2>NUL', $out, $rc);
    if ($rc !== 0) return null;
    foreach ($out as $line) {
        if (preg_match('/^\s*Print Name\s*:\s*(.+?)\s*$/i', $line, $m)) {
            return $m[1];
        }
    }
    return null;
}

/** Case-insensitive, separator-insensitive path equality for Windows. */
function win_path_eq(string $a, string $b): bool {
    $n = fn($p) => strtolower(str_replace('/', '\\', rtrim($p, "/\\ \t\n\r\0\x0B")));
    return $n($a) === $n($b);
}
